services:
  nginx:
  
    container_name: nginx_bookstore_compose

    build:
      context: .

    ports:
      - 127.0.0.1:8080:8080

    networks:
      - bookstore-net



  mysql:

    container_name: mysql_bookstore_compose

    build:
      context: ./db

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      bookstore-net:
        ipv4_address: 172.16.16.16

    secrets:
      - mysql_root_password



networks:
  bookstore-net:

    driver: bridge

    enable_ipv6: false

    ipam:
      config:
        - subnet: 172.16.16.0/24
          ip_range: 172.16.16.0/27
          gateway: 172.16.16.1


volumes:
  mysql_data:


secrets:
  mysql_root_password:
    file: ./db/root_password.txt
    


    
